name: WorkflowCall - Deploy to GCS Bucket
on:
  workflow_call:
    inputs:
      environment:
        type: string
        description: Deployment environment
        required: true
      dir:
        type: string
        required: true
      skip:
        type: boolean
        default: false
    # secrets:
    #   sec:
    #     required: true
jobs:
  before-deploy:
    runs-on: ubuntu-latest
    if: ${{ !inputs.skip }}
    steps:
      - name: Test
        run: exit 0
  terraform-deploy:
    needs: before-deploy
    # if: ${{ cancelled() || contains(needs.*.result, 'cancelled') || contains(needs.*.result, 'failure') }}
    environment:
      name: ${{ inputs.environment }}
    name: Terraform Deploy
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.dir }}
    steps:
      # - run: |
      #     echo "Some workflows have failed!"
      #     exit 1
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test
        run: pwd
      - name: See files
        run: ls -la
      - run: |
          if [[ '${{ secrets.SEC }}' == 'SEC_VALUE_DEV' ]]; then
            echo "dev"
          else
            echo "not dev"
            exit 1
          fi