on:
  push:
    branches:
      - '**'
jobs:
  deploy_dev:
    runs-on: ubuntu-latest
    environment: dev
    secrets: inherit
    steps:
      - uses: ./.github/workflows/_deploy.yml
        with:
          environment: dev
          var: ${{ vars.VAR }}