on:
  push:
    branches:
      - '**'
    paths:
      - "apps/*/supabase/**"
jobs:
  # test-root-workflow:
  #   runs-on: ubuntu-latest
  #   environment:
  #     name: dev
  #   steps:
  #     - name: Test
  #       run: echo "${{ vars.VAR }}"

  test-changed-files:
    runs-on: ubuntu-latest
    outputs:
      apps: ${{ steps.changed-dirs.outputs.apps }}
    steps:
      - uses: 'actions/checkout@v4'
      - name: Run changed-files with dir_names
        id: changed-files-dir-names
        uses: tj-actions/changed-files@v45
        with:
          files: |
            apps/*/supabase/**
          dir_names: "true"
      - name: List all changed dirs
        id: changed-dirs
        env:
          DIRS: ${{ steps.changed-files-dir-names.outputs.all_changed_files }}
        run: |
          for DIR in ${DIRS}; do
            SEGMENT=$(echo "$DIR" | cut -d'/' -f2)
            RESULT+=("$SEGMENT")
            echo "$SEGMENT was changed"
          done
          echo "apps="$(jq -c -n '$ARGS.positional' --args "${RESULT[@]}")
          echo "apps="$(jq -c -n '$ARGS.positional' --args "${RESULT[@]}") >> $GITHUB_OUTPUT

  deploy-dev:
    needs: test-changed-files
    if: ${{ needs.test-changed-files.outputs.apps != '[]' && needs.test-changed-files.outputs.apps != '' }}
    strategy:
      matrix:
        app: ${{ fromJson(needs.test-changed-files.outputs.apps) }}
    secrets: inherit
    uses: ./.github/workflows/_deploy.yml
    with:
      environment: dev-${{ matrix.app }}
      dir: apps/${{ matrix.app }}